version: '1'
services:
  product-app:
    container_name: product-web-app
    hostname: product-app
    environment:
      - API_URL=product-api:8080
    ports:
      - "3000:3000"
    image: product-web-app
    depends_on:
      - api
  api:
    container_name: product-api
    hostname: product-api
    environment:
      - DB_USERNAME=$DB_USERNAME
      - DB_PASSWORD=$DB_PASSWORD
      - DB_HOST=$DB_HOST
      - DB_NAME=$DB_NAME
    ports:
      - "8080:8080"
    image: product-api
    depends_on:
      - db
  db:
    image: mysql
    container_name: MYSQLDB
    hostname: mysqldb
    volumes:
      - ./product-backend/scripts:/tmp/scripts
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password --init-file="/tmp/scripts/1_init.sql"
    environment:
      MYSQL_ROOT_PASSWORD: $DB_PASSWORD